# Generated by Django 3.0.8 on 2021-09-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210919_1942'),
        ('quiz', '0010_auto_20210919_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
