# Generated by Django 3.0.8 on 2021-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default=1, max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default=1, null=True, upload_to='profile_pic/Student/'),
        ),
    ]
